version: 2.1

orbs:
  macos: circleci/macos@2

jobs:
  macos-vnc:
    macos:
      xcode: 16.4.0
    resource_class: m4pro.medium

    steps:
      - checkout

      - run:
          name: Show macOS info
          command: |
            sw_vers
            uname -a
            whoami
            xcodebuild -version

      - macos/enable-vnc:
          username: vncuser
          password: ci123456

      - run:
          name: Keep VM alive
          no_output_timeout: 30m
          command: |
            echo "VNC is enabled."
            echo "Username: vncuser"
            echo "Password: ci123456"
            while true; do
              echo "VM alive: $(date)"
              sleep 60
            done

workflows:
  test:
    jobs:
      - macos-vnc
